config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :menus, only: [:index, :create, :new, :edit, :update]
  resources :pages, only: [:index, :create, :new, :edit, :update]
  resources :users, only: [:index, :create, :new, :edit, :update]
  resources :banners, only: [:index, :create, :new, :edit, :update]
  resources :orders, only: [:index, :show ]

  get 'product/:id/delete', to: 'products#delete', as: 'product_delete'
  get 'menu/:id/delete', to: 'menus#delete', as: 'menu_delete'
  get 'page/:id/delete', to: 'pages#delete', as: 'page_delete'
  get 'user/:id/delete', to: 'users#delete', as: 'user_delete'
  get 'banner/:id/delete', to: 'banners#delete', as: 'banner_delete'
  get 'order/:id/delete', to: 'orders#delete', as: 'order_delete'
  get 'order/:id/:status/update_status', to: 'orders#update_status', as: 'order_update_status'

  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :subscribers, only: [ :create ]
  end

  resource :unsubscribe, only: [ :show ]

  get 'admin', to: 'dashboard#index', as: 'dashboard'
  get 'session/logout', to: 'sessions#logout', as: 'session_logout'
  
  get '/', to: 'home#index', as: 'home_index'
  get '/product/:id/:slug', to: 'home#detail', as: 'product_detail'
  get '/products/:id/:slug', to: 'home#menu_products', as: 'product_menu'
  get '/page/:slug', to: 'home#page_detail', as: 'page_detail'
  get '/search', to: 'home#search', as: 'home_search'

  get 'login', to: 'home#login', as: 'home_login'
  post 'login', to: 'home#customer_login', as: 'home_customer_login'
  get 'register', to: 'home#register', as: 'home_register'
  post 'register', to: 'home#customer_register', as: 'home_customer_register'
  get 'logout', to: 'home#logout', as: 'home_logout'

  get 'account', to: 'account#index', as: 'account_index'
  get 'account/order', to: 'account#order', as: 'account_order'
  get 'account/order_detail/:id', to: 'account#order_detail', as: 'account_order_detail'
  get 'account/edit', to: 'account#edit', as: 'account_edit'
  post 'account/update', to: 'account#update', as: 'account_update'
  get 'account/password', to: 'account#password', as: 'account_password'
  post 'account/password_update', to: 'account#password_update', as: 'account_password_update'
  get 'account/logout', to: 'account#logout', as: 'account_logout'

  get 'cart', to: 'cart#index', as: 'cart_index'
  post 'add_to_cart', to: 'cart#add', as: 'cart_add'
  post 'update_cart', to: 'cart#update', as: 'cart_update'
  post 'remove_from_cart', to: 'cart#remove', as: 'cart_remove'
  get 'checkout', to: 'cart#checkout', as: 'cart_checkout'
  post 'checkout', to: 'cart#pay', as: 'cart_pay'
  get 'thank_you', to: 'cart#thank_you', as: 'cart_thank_you'

  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  allow_unauthenticated_access
  layout 'layouts/frontend/app'

  def index
    @products_giam_gia = Product.where(menu_id: 7)
                                .or(Product.where(menu_id: Menu.where(menu_fk: 7).pluck(:id)))
                                .or(Product.where("discount > ?", 0))
                                .order(id: :desc)
                                .limit(4)

    @products_new = Product.order(id: :desc).limit(8)

    @products_view = Product.order(view: :desc).limit(8)

    child_menu_sn_ids = Menu.where(menu_fk: 1).pluck(:id)
    @products_sinh_nhat = Product.where(menu_id: [1, *child_menu_sn_ids]).order(id: :desc).limit(4)

    child_menu_kt_ids = Menu.where(menu_fk: 2).pluck(:id)
    @products_khai_truong = Product.where(menu_id: [2, *child_menu_kt_ids]).order(id: :desc).limit(8)

    child_menu_hl_ids = Menu.where(menu_fk: 3).pluck(:id)
    @products_hoa_lan = Product.where(menu_id: [3, *child_menu_hl_ids]).order(id: :desc).limit(8)

    @banners = Banner.where(active: 1).order(:item)
  end


  def detail
    @product = Product.find(params[:id])
    @product.increment!(:view)
    menu = Menu.includes(:children).find(@product.menu_id)

    menu_ids = [menu.id]
    menu_ids += menu.children.pluck(:id) if menu.children.present?

    @products = Product.where(menu_id: menu_ids)
                       .where.not(id: @product.id)
                       .order(id: :desc)
                       .limit(4)

    @top_view_products = Product.where.not(id: @product.id).order(view: :desc).limit(4)
  end

  def menu_products
    @menu = Menu.includes(:children).find(params[:id])
    menu_ids = [@menu.id] + @menu.children.pluck(:id)
    @per_page = params[:per_page].to_i > 0 ? params[:per_page].to_i : 20
  
    @sort = params[:sort].to_s.strip || "Mặc định"
    
    order_query = case @sort
                  when "Tên (A - Z)"
                    "name ASC"
                  when "Tên (Z - A)"
                    "name DESC"
                  when "Giá (Thấp - Cao)"
                    Arel.sql("CAST(price AS DECIMAL) ASC")
                  when "Giá (Cao - Thấp)"
                    Arel.sql("CAST(price AS DECIMAL) DESC")
                  else
                    "id DESC"
                  end

    @products = Product.where(menu_id: menu_ids)
                        .order(order_query)
                        .page(params[:page])
                        .per(@per_page)
  end

  def page_detail
    @page = Page.find_by(slug: params[:slug])
    if @page.nil?
      redirect_to root_path, alert: "Page not found!"
    end
  end

  def search
    @q = params[:q].to_s.strip
    @per_page = params[:per_page].to_i > 0 ? params[:per_page].to_i : 20
  
    @sort = params[:sort].to_s.strip || "Mặc định"
    
    order_query = case @sort
                  when "Tên (A - Z)"
                    "name ASC"
                  when "Tên (Z - A)"
                    "name DESC"
                  when "Giá (Thấp - Cao)"
                    Arel.sql("CAST(price AS DECIMAL) ASC")
                  when "Giá (Cao - Thấp)"
                    Arel.sql("CAST(price AS DECIMAL) DESC")
                  else
                    "id DESC"
                  end
  
    @products = Product.where("name ILIKE ?", "%#{@q}%")
                       .order(order_query)
                       .page(params[:page])
                       .per(@per_page)
  end
  
  def register
    @user = User.new
  end

  def customer_register
    if User.exists?(email_address: user_params[:email_address])
      flash.now[:alert] = 'Email đã tồn tại. Vui lòng sử dụng một email khác.'
      @user = User.new
      render :register
    else
      @user = User.new(user_params)
      @user.super_user ||= 2
      if @user.save
        redirect_to home_login_path, notice: 'Đăng ký thành công.'
      else
        alert = @user.errors.full_messages.to_sentence
        flash.now[:alert] = alert
        @user = User.new
        render :register
      end
    end
  end

  def customer_login
    if user = User.authenticate_by(params.permit(:email_address, :password))
      if user.super_user == 2
        session[:user_id] = user.id

        if session[:cart] && session[:cart].any?
          session[:cart].each do |product_id, quantity|
            Cart.create(
              user_id: user.id,
              product_id: product_id.to_i,
              quantity: quantity.to_i
            )
          end
  
          session[:cart] = nil
        end
        redirect_to account_index_path
      else
        redirect_to home_login_path, alert: "Thử lại địa chỉ email hoặc password khác."
      end
    else
      redirect_to home_login_path, alert: "Thử lại địa chỉ email hoặc password khác."
    end
  end

  def customer_logout
    reset_session
    session[:cart] = nil
    redirect_to home_index
  end


  private

    def user_params
      params.require(:user).permit(:email_address, :password, :password_confirmation, :name, :phone)
    end
    
end

app/views/home/_aside.html.erb
<aside id="column-right" class="col-3 d-none d-md-block">
    <div class="list-group mb-3">
      <%= link_to "Đăng nhập", home_login_path, class: "list-group-item" %>
      <%= link_to "Đăng ký", home_register_path, class: "list-group-item" %>
      <%= link_to "Đã quên mật khẩu", new_password_path, class: "list-group-item" %>
      <%= link_to "Tài khoản của tôi", home_login_path, class: "list-group-item" %>
      <%= link_to "Lịch sử đơn hàng", home_login_path, class: "list-group-item" %>
    </div>
  </aside>
  

app/views/home/_breadcrumb.html.erb
<ul class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to home_index_path do %>
        <i class="fas fa-home"> </i>
      <% end %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to "Tài khoản", home_login_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to "Đăng ký", home_register_path %>
    </li>
</ul>
  

app/views/home/detail.html.erb
<%= content_for :title, @product.name %>
<main>
  <div id="product-info" class="container mt-4">
    <%= render "layouts/frontend/alert" %>

    <div class="row">
      <div id="content" class="col">
        <div class="row mb-3">
          <div class="col-sm">
            <div class="image magnific-popup">
              <% cache [:product_image, @product] do %>
              <a href="<%= url_for(@product.featured_image) %>" title="<%= @product.name %>">
                <img src="<%= url_for(@product.featured_image) %>" title="<%= @product.name %>" alt="<%= @product.name %>" class="img-thumbnail mb-3" />
              </a>
              <% end %>
            </div>
          </div>
          <div class="col-sm po-relative">
            <h1 class="product-name"><%= @product.name %></h1>
            <ul class="list-unstyled price-box">
              <% if @product.discount > 0 %>
                <li>
                  <h3><span class="price-old"><%= number_to_currency(@product.price.to_f, unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span></h3>
                </li>
                <li>
                  <h3><span class="price-new"><%= number_to_currency(@product.price.to_f - (@product.price.to_f * (@product.discount / 100.0)), unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span></h3>
                </li>
                <span class="percent_off"><%= @product.discount %> % GIẢM</span>
              <% else %>
                <li>
                  <h3><span class="price-new"><%= number_to_currency(@product.price.to_f, unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span></h3>
                </li>
              <% end %>
            </ul>

            <div class="coupon_box">
              <div class="coupon_slider"></div>
              <div class="coupon_box_detail"></div>
            </div>

            <div class="call_us_box">
              Gọi ngay: <span class="call-us">1900 123 456</span>
            </div>

            <div class="call_us_box call_social">
                Chat ngay:
                <a href="" ><img src="https://www.flowercorner.vn/image/icon/ms.png" alt="messenger" /></a>
                <a href="" ><img src="https://www.flowercorner.vn/image/icon/zalo.png" alt="zalo" /></a>
                <a href="" ><img src="https://www.flowercorner.vn/image/icon/zalo.png" alt="zalo" /></a>
                <a href="" ><img src="https://www.flowercorner.vn/image/icon/zalo.png" alt="zalo" /></a>
                <a href="" ><img src="https://www.flowercorner.vn/image/icon/zalo.png" alt="zalo" /></a>
            </div>
            <% if @product.inventory_count? %>
              <div class="call_us_box ship_box">
                Vận chuyển: <span class="free-ship">Miễn phí giao hoa khu vực nội thành TP.HCM & Hà Nội</span>
              </div>
              <div class="ship_box_detail row">
                <div class="col-sm-6 mt-2 mb-2">
                  <select class="form-select ship-to-region"></select>
                </div>
                <div class="col-sm-6 mt-2 mb-2">
                  <select class="form-select ship-to-district"></select>
                </div>
                <p class="ship_message">Phí giao hàng: <span class="ship_fee">Miễn phí!</span></p>
              </div>
              <p><b><u>In stock</u> : <%= @product.inventory_count %></b></p>
              <div id="product">
                <%= form_with url: cart_add_path, method: :post, local: true do |f| %>
                  <div class="mb-3">
                    <p class="mb-0"><label for="input-quantity" class="form-label">Qty</label></p>
                    <%= f.number_field :quantity, min: 1, value: 1, size: 2, id: "input-quantity", class: "form-control", style: 'width: 50px; display: inline-block; vertical-align: bottom;' %>
                    <%= hidden_field_tag :product_id, @product.id, id: "input-product-id" %>
                    <%= hidden_field_tag :action_type, "order", id: "input-action-type" %>

                    <%= f.submit "Đặt hàng", class: "btn btn-primary btn-lg btn-block", style: 'background: orange; border: 2px solid orange;' %>
                    <%= button_tag "Đặt nhanh", type: "submit", class: "btn btn-primary btn-lg btn-block", style: 'background: #e55f00; border: 2px solid #e55f00;', onclick: "document.getElementById('input-action-type').value = 'quick_order';" %>                  
                  </div>
                <% end %>
              </div>
              <div class="pdp-featured">
                <div class="pdp-featured-item">
                  <img src="https://www.flowercorner.vn/image/icon/60mins.png" alt="Giao hoa nhanh 60 phút" />
                  <span>Giao hoa NHANH trong 60 phút</span>
                </div>
                <div class="pdp-featured-item">
                  <img src="https://www.flowercorner.vn/image/icon/freegifts.png" alt="Tặng miễn phí thiệp hoặc banner" />
                  <span>Tặng miễn phí thiệp hoặc banner</span>
                </div>
              </div>
            <% else %>
              <b>
                <p>Out of stock</p>
                <p>Email me when available.</p>
              </b>
              
              <%= form_with model: [@product, Subscriber.new], class: "d-flex align-items-center gap-2" do |form| %>
                <%= form.email_field :email, placeholder: "you@example.com", required: true, class: 'form-control me-2' %>
                <%= form.submit "Submit", class: "btn btn-primary" %>
              <% end %>

            <% end %>
            
          </div>
        </div>

        <ul class="nav nav-tabs">
          <li class="nav-item"><a href="#tab-description" data-bs-toggle="tab" class="nav-link active">Mô tả sản phẩm</a></li>
        </ul>

        <div class="tab-content">
          <% cache [:product_description, @product] do %>
          <div id="tab-description" class="tab-pane fade show active mb-4">
            <%= raw @product.description %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <% if @products.any? %>
    <h3>Sản phẩm liên quan</h3>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4">
      <% @products.each do |item| %>
        <div class="col">
          <div class="product-thumb po-relative">
            <div class="image p-relative">
              <a href="<%= product_detail_path(id: item.id, slug: item.slug) %>">
                <img src="<%= url_for(item.featured_image) %>" alt="<%= item.name %>" width="261" height="326" class="img-fluid" />
                <% if item.discount > 0 %>
                  <span class="percent-off-rounded"><%= item.discount %>% GIẢM</span>
                <% end %>
              </a>
            </div>
            <div class="content">
              <div class="description">
                <h3><a href="<%= product_detail_path(id: item.id, slug: item.slug) %>" class="product-item-title"><%= item.name %></a></h3>
                <div class="price">
                  <% if item.discount > 0 %>
                    <span class="price-new"><%= number_to_currency(item.price.to_f - (item.price.to_f * (item.discount / 100.0)), unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                    <span class="price-old"><%= number_to_currency(item.price.to_f, unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                  <% else %>
                    <span class="price-new"><%= number_to_currency(item.price.to_f, unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                  <% end %>
                </div>
              </div>
              <div class="buynow-button text-center">
                <a href="<%= product_detail_path(id: item.id, slug: item.slug) %>">ĐẶT HÀNG</a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br>
    <br>
    <% end %>
    <h3>Sản phẩm được xem nhiều nhất</h3>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4">
      <% @top_view_products.each do |item| %>
        <div class="col">
          <div class="product-thumb po-relative">
            <div class="image p-relative">
              <a href="<%= product_detail_path(id: item.id, slug: item.slug) %>">
                <img src="<%= url_for(item.featured_image) %>" alt="<%= item.name %>" width="261" height="326" class="img-fluid" />
                <% if item.discount > 0 %>
                  <span class="percent-off-rounded"><%= item.discount %>% GIẢM</span>
                <% end %>
              </a>
            </div>
            <div class="content">
              <div class="description">
                <h3><a href="<%= product_detail_path(id: item.id, slug: item.slug) %>" class="product-item-title"><%= item.name %></a></h3>
                <div class="price">
                  <% if item.discount > 0 %>
                    <span class="price-new"><%= number_to_currency(item.price.to_f - (item.price.to_f * (item.discount / 100.0)), unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                    <span class="price-old"><%= number_to_currency(item.price.to_f, unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                  <% else %>
                    <span class="price-new"><%= number_to_currency(item.price.to_f, unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                  <% end %>
                </div>
              </div>
              <div class="buynow-button text-center">
                <a href="<%= product_detail_path(id: item.id, slug: item.slug) %>">ĐẶT HÀNG</a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div id="quickOrder" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">ĐẶT HOA NHANH</h4>
        </div>
        <form id="quickOrderForm" novalidate>
          <div class="modal-body">
            <div>
              Quý khách vui lòng điền thông tin bên dưới và bấm nút đặt hàng, nhân viên chúng tôi sẽ gọi quý khách
              trong ít phút để hỗ trợ đặt hàng:
            </div>

            <div class="row">
              <div class="col-md-12 order-md-1">
                <input type="hidden" class="form-control" id="product-name-model"
                  value="Kiss Me - Mã sản phẩm: BOUQUET-9030">
                <div class="row mt-3">
                  <div class="col-md-6 mb-6">
                    <div class="mb-3">
                      <label for="sender">Họ tên</label>
                      <input type="text" class="form-control" id="sender" required>
                    </div>
                  </div>
                  <div class="col-md-6 mb-6">
                    <div class="mb-3">
                      <label for="senderphone">Số điện thoại</label>
                      <input type="text" class="form-control" id="senderphone" placeholder="" value="" required>
                    </div>
                  </div>

                  <div class="col-md-12 mb-6">
                    <div class="g-recaptcha" data-sitekey="6LeQyycpAAAAAMghgRAuDG-4q6XWEeVxnJtIgY1Y"></div>
                  </div>

                </div>
                <div class="row mt-3">
                  <div class="col-md-12 mb-6">
                    * Đặt hoa nhanh từ 7:00-20:00
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default btn-sm" data-bs-dismiss="modal">HUỶ</button>
            <button class="btn btn-primary btn-lg btn-block btn-sm" type="submit">GỬI ĐƠN HÀNG</button>
          </div>
        </form>
      </div>

    </div>
  </div>

  <script src="/assets/frontend/js/detail/script1.js"></script>
</main>

app/views/home/login.html.erb
<%= content_for :title, "Đăng nhập" %>
<main>
    <div id="account-login" class="container">
      <%= render 'home/breadcrumb' %>
      <%= render 'layouts/frontend/alert' %>
      <div class="row">
        <div id="content" class="col">
          <div class="row">
            <div class="col-sm-6">
              <div class="card mb-3">
                <div class="card-body">
                  <h2>Khách hàng mới</h2>
                  <p><strong>Đăng ký tài khoản</strong></p>
                  <p>Bằng cách tạo tài khoản, bạn sẽ có thể mua sắm nhanh hơn, cập nhật trạng thái đơn hàng và theo dõi các đơn hàng bạn đã thực hiện trước đó.</p>
                  <%= link_to "Tiếp tục", home_register_path, class: "btn btn-primary" %>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="card mb-3">
                <div class="card-body">
                    <%= form_with url: home_customer_login_path do |f| %>
                      <h2>Phản hồi khách hàng</h2>
                        <p><strong>Tôi là một khách hàng cũ</strong></p>
                      <div class="mb-3">
                        <%= f.label :email_address, "Địa chỉ email", class: "col-form-label" %>
                        <%= f.text_field :email_address, placeholder: "Địa chỉ email", id: "input-email", class: "form-control" %>
                      </div>
                      <div class="mb-3">
                        <%= f.label :password, "Mật khẩu", class: "col-form-label" %>
                        <%= f.password_field :password, placeholder: "Mật khẩu", id: "input-password", class: "form-control" %><br/>
                        <%= link_to "Đã quên mật khẩu", new_password_path %>
                      </div>
                    <%= f.submit "Đăng nhập", class: "btn btn-primary" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%= render 'home/aside' %>
      </div>
    </div>
  </main>
  

app/views/home/logout.html.erb
<%= content_for :title, "Đăng xuất" %>
<main>
    <div id="common-success" class="container mt-4">
        <div class="row">
            <div id="content" class="col text-center">
                <p> Bạn đã đăng xuất khỏi tài khoản thành công. </p>
                <div class="d-inline-block pt-2 pd-2 w-100 ">
                    <div class="text-center"><a href="/" class="btn btn-primary">Tiếp tục</a></div>
                </div>
            </div>
            <%= render 'home/aside' %>
        </div>
    </div>
</main>

app/views/home/menu_products.html.erb
<%= content_for :title, @menu.name %>
<style>
  form#search {
      all: unset;
      all: revert;
      display: contents;
  }
</style>
<div id="product-category" class="container">
    <div class="row">
      <div id="content" class="col">
        <h1><span class="category-title"><%= @menu.name %></span></h1>
  
        <div id="display-control" class="row">
          <%= form_with url: product_menu_path, method: :get, local: true, id: 'search' do %>
            <div class="col-lg-3 offset-lg-6 me-3">
                <div class="input-group mb-3">
                <div class="input-group">
                    <label for="sort" class="input-group-text">Sắp xếp theo</label>
                    <select id="sort" name="sort" class="form-control" onchange="this.form.submit()" style="background: white">
                        <% ["Mặc định", "Tên (A - Z)", "Tên (Z - A)", "Giá (Thấp - Cao)", "Giá (Cao - Thấp)"].each do |value| %>
                            <option value="<%= value %>" <%= 'selected' if @sort == value %>>
                                <%= value %>
                            </option>
                        <% end %>
                    </select>
                </div>
                </div>
            </div>
          
            <div class="col-lg-2 col-6">
              <div class="input-group mb-3">
                <div class="input-group">
                  <input type="text" name="q" value="<%= @q %>" hidden>
                  <label for="per_page" class="input-group-text">Số lượng</label>
                  <select id="per_page" name="per_page" class="form-control" onchange="this.form.submit()" style="background: white">
                      <% [12, 20, 28].each do |value| %>
                          <option value="<%= value %>" <%= 'selected' if @per_page == value %>>
                              <%= value %>
                          </option>
                      <% end %>
                  </select>
                </div>
              </div>
            </div>
          <% end %>
        </div>
  
        <div id="product-list" class="row row-cols-2 row-cols-sm-2 row-cols-md-2 row-cols-lg-4">
          <% @products.each do |product| %>
            <div class="col mb-3">
              <%= form_with url: "#", method: :post do |form| %>
                <div class="product-thumb po-relative">
                  <div class="image p-relative">
                    <%= link_to product_detail_path(id: product.id, slug: product.slug) do %>
                      <img src="<%= url_for(product.featured_image) %>" alt="<%= product.name %>" title="<%= product.name %>" class="img-fluid lozad" width="261" height="326">
                      <% if product.discount > 0 %>
                        <span class="percent-off-rounded"><%= product.discount %>%<br />GIẢM</span>
                      <% end %>
                    <% end %>
                  </div>
  
                  <div class="content">
                    <div class="description">
                      <h3><%= link_to product.name, product_detail_path(id: product.id, slug: product.slug), class: "product-item-title" %></h3>
                      <div class="price">
                        <% if product.discount > 0 %>
                          <span class="price-new"><%= number_to_currency(product.price.to_f - (product.price.to_f * (product.discount / 100.0)), unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                          <span class="price-old"><%= number_to_currency(product.price.to_f, unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                        <% else %>
                          <span class="price-new"><%= number_to_currency(product.price.to_f, unit: ' VND', format: '%n %u', precision: 0, precision: 0) %></span>
                        <% end %>
                      </div>
                    </div>
                    <div class="buynow-button text-center">
                      <%= link_to 'ĐẶT HÀNG', product_detail_path(id: product.id, slug: product.slug) %>
                    </div>
                  </div>
  
                  <%= form.hidden_field :product_id, value: product.id %>
                  <%= form.hidden_field :quantity, value: 1 %>
                </div>
              <% end %>
            </div>
          <% end %>
  
          <% if @products.empty? %>
            <p>No products found.</p>
          <% end %>
        </div>
      </div>
  
      <div style="justify-content: center; display: flex;">
        <%= paginate @products %>
      </div>
    </div>
</div>

app/views/home/page_detail.html.erb
<%= content_for :title, @page.name %>
<style>
    figure.attachment.attachment--preview, h1 {
        text-align: center;
    }
</style>
<div id="information-information" class="container">
    <div class="row">
        <% cache "page_#{@page.cache_key}" do %>
            <div id="content" class="col">
                <%= raw @page.description %>
            </div>
        <% end %>
    </div>
</div>