config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :menus, only: [:index, :create, :new, :edit, :update]
  resources :pages, only: [:index, :create, :new, :edit, :update]
  resources :users, only: [:index, :create, :new, :edit, :update]
  resources :banners, only: [:index, :create, :new, :edit, :update]
  resources :orders, only: [:index, :show ]

  get 'product/:id/delete', to: 'products#delete', as: 'product_delete'
  get 'menu/:id/delete', to: 'menus#delete', as: 'menu_delete'
  get 'page/:id/delete', to: 'pages#delete', as: 'page_delete'
  get 'user/:id/delete', to: 'users#delete', as: 'user_delete'
  get 'banner/:id/delete', to: 'banners#delete', as: 'banner_delete'
  get 'order/:id/delete', to: 'orders#delete', as: 'order_delete'
  get 'order/:id/:status/update_status', to: 'orders#update_status', as: 'order_update_status'

  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :subscribers, only: [ :create ]
  end

  resource :unsubscribe, only: [ :show ]

  get 'admin', to: 'dashboard#index', as: 'dashboard'
  get 'session/logout', to: 'sessions#logout', as: 'session_logout'
  
  get '/', to: 'home#index', as: 'home_index'
  get '/product/:id/:slug', to: 'home#detail', as: 'product_detail'
  get '/products/:id/:slug', to: 'home#menu_products', as: 'product_menu'
  get '/page/:slug', to: 'home#page_detail', as: 'page_detail'
  get '/search', to: 'home#search', as: 'home_search'

  get 'login', to: 'home#login', as: 'home_login'
  post 'login', to: 'home#customer_login', as: 'home_customer_login'
  get 'register', to: 'home#register', as: 'home_register'
  post 'register', to: 'home#customer_register', as: 'home_customer_register'
  get 'logout', to: 'home#logout', as: 'home_logout'

  get 'account', to: 'account#index', as: 'account_index'
  get 'account/order', to: 'account#order', as: 'account_order'
  get 'account/order_detail/:id', to: 'account#order_detail', as: 'account_order_detail'
  get 'account/edit', to: 'account#edit', as: 'account_edit'
  post 'account/update', to: 'account#update', as: 'account_update'
  get 'account/password', to: 'account#password', as: 'account_password'
  post 'account/password_update', to: 'account#password_update', as: 'account_password_update'
  get 'account/logout', to: 'account#logout', as: 'account_logout'

  get 'cart', to: 'cart#index', as: 'cart_index'
  post 'add_to_cart', to: 'cart#add', as: 'cart_add'
  post 'update_cart', to: 'cart#update', as: 'cart_update'
  post 'remove_from_cart', to: 'cart#remove', as: 'cart_remove'
  get 'checkout', to: 'cart#checkout', as: 'cart_checkout'
  post 'checkout', to: 'cart#pay', as: 'cart_pay'
  get 'thank_you', to: 'cart#thank_you', as: 'cart_thank_you'

  root "home#index"
end

app/views/layouts/frontend/_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<% flash.clear %>

app/views/layouts/frontend/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <img class="mb-3 lozad" src="https://www.flowercorner.vn/image/catalog/1px.webp"
                    data-src="https://flowercorner.b-cdn.net/image/catalog/common/shop-hoa-tuoi-flowercorner-logo.png.webp"
                    width="255" height="53" alt="shop hoa Flowercorner.vn" title="shop hoa Flowercorner.vn">
                Hotline: 1900 123 456 - 1900 789 123
                Email: example@flowercorner.vn
                <div class="row mt-3 mb-3">
                    <div class="col-md-5">
                        <img class="lozad" src="https://www.flowercorner.vn/image/catalog/1px.webp"
                            data-src="https://flowercorner.b-cdn.net/image/catalog/common/app/qr.png.webp"
                            width="92" height="114" alt="quét để tải app FlowerCorner"
                            title="quét để tải app FlowerCorner">
                    </div>
                    <div class="col-md-7">
                        <p>Tải ứng dụng ngay!</p>
                        <p>
                            <a><img class="lozad"
                                    src="https://www.flowercorner.vn/image/catalog/1px.webp"
                                    data-src="https://flowercorner.b-cdn.net/image/catalog/common/app/appstore.png.webp"
                                    width="139" height="35" alt="FlowerCorner trên app store"
                                    title="FlowerCorner trên app store"></a>
                        </p>
                        <p></p>
                        <p>
                            <a><img
                                    class="lozad" src="https://www.flowercorner.vn/image/catalog/1px.webp"
                                    data-src="https://flowercorner.b-cdn.net/image/catalog/common/app/gplay.png.webp"
                                    width="139" height="35" alt="FlowerCorner trên Google play"
                                    title="FlowerCorner trên Google play"></a>
                        </p>
                        <p></p>
                    </div>
                </div>
                <div>
                    <p>
                        <a>
                            <img class="lozad" src="https://www.flowercorner.vn/image/catalog/1px.webp"
                                data-src="https://flowercorner.b-cdn.net/image/catalog/common/app/logoSaleNoti.png.webp"
                                alt="da khai bao" width="255" height="96">
                        </a>
                    </p>
                </div>
            </div>
            <div class="col-sm-3">
                <h5 class="mb-3">CHĂM SÓC KHÁCH HÀNG</h5>
                <div>
                    <% @pages.each do |page| %>
                        <p><%= link_to page.name, page_detail_path(slug: page.slug), rel: "nofollow" %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-sm-2">
                <h5 class="mb-3">THEO DÕI</h5>
                <div>
                    <p><a href="#" rel="nofollow"> <i
                                class="fa-brands fa-facebook" aria-hidden="true"></i> Facebook</a> </p>
                    <p><a href="#" rel="nofollow"> <i
                                class="fa-brands fa-twitter-square" aria-hidden="true"></i> Twitter</a> </p>
                    <p><a href="#" rel="nofollow"> <i
                                class="fa-brands fa-instagram" aria-hidden="true"></i> Instagram</a> </p>
                    <p><a href="#" rel="nofollow"> <i
                                class="fa-brands fa-linkedin" aria-hidden="true"></i> Linkedin</a> </p>
                    <p><a href="#" rel="nofollow"> <i
                                class="fa-brands fa-youtube" aria-hidden="true"></i> Youtube</a> </p>
                </div>
            </div>
            <div class="col-sm-4">
                <h5 class="mb-3">SHOP HOA FLOWERCORNER</h5>
                <p><b>Cửa hàng chính:</b>: <a href="#">Nguyễn Thái Học, Vũng Tàu</a></p>
                <br>

                <p><b>Cửa Hàng TP.HCM</b>: <a href="#">Ba Cu, Vũng Tàu</a></p>
                <br>

                <p><b>Chi nhánh Hà Nội</b>: <a href="#" rel="follow">Trương Công Định, Vũng Tàu</a> </p>
                <p>CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ ABC<br />Mã số thuế: 123 456</p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/frontend/_head.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<title><%= yield :title %> | Flowercorner</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="shortcut icon" type="image/jpg" href="/Logo-icon.png" />

<!-- <script src="/assets/frontend/js/index/script1.js"></script> -->
<script src="/assets/frontend/js/index/script2.js"></script>
<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet"> -->
 <link href="/assets/frontend/fontawesome-free-6.7.2-web/css/all.min.css" rel="stylesheet">

<link rel="stylesheet" href="/assets/frontend/css/style1.css">
<!-- <link rel="preload" href="https://www.flowercorner.vn/catalog/view/stylesheet/fonts/fontawesome/css/all.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript>
<link rel="stylesheet" href="https://flowercorner.b-cdn.net/catalog/view/stylesheet/fonts/fontawesome/css/all.min.css">
</noscript> -->
<link rel="preload" href="/assets/frontend/css/font-Montserrat.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript>
<link rel="stylesheet" href="/assets/frontend/css/font-Montserrat.css">
</noscript>
<link rel="stylesheet" href="/assets/frontend/css/style2.css">
<link rel="stylesheet" href="/assets/frontend/css/style3.css">
<script src="/assets/frontend/js/index/script3.js"></script>
<script src="/assets/frontend/js/index/script4.js"></script>
<script src="/assets/frontend/js/index/script5.js"></script>
<script src="/assets/frontend/js/index/script6.js"></script>
<link rel="stylesheet" href="/assets/backend/themes/loadingg.css">
<!-- <script src="/assets/frontend/js/index/script7.js"></script> -->

app/views/layouts/frontend/_header.html.erb
<header>
    <div class="container">
        <div class="row">
            <div class="col-md-4 mt-2">
                <div class="go-social">
                    <a href="">
                        <i class="fa-brands fa-facebook fa-2xl"></i>
                    </a>
                    <a href="">
                        <i class="fa-brands fa-twitter fa-2xl"></i>
                    </a>
                    <a href="">
                        <i class="fa-brands fa-instagram fa-2xl"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div id="logo">
                    <%= link_to image_tag("/shop-hoa-tuoi-flowercorner-logo.png.webp", 
                        title: "FlowerCorner.vn - Shop hoa tươi", 
                        alt: "FlowerCorner.vn - Shop hoa tươi", 
                        class: "img-fluid", 
                        width: 300, 
                        height: 62), home_index_path %>
                </div>
            </div>
            <div class="col-md-4 mt-2 hide-mobile">
                <div class="row">
                    <div class="col-sm-10">
                        <div id="search" class="input-group mb-3">
                          <%= form_with url: home_search_path, method: :get, local: true, class: "w-100" do %>
                            <input type="text" name="q" placeholder="Tìm kiếm" class="form-control form-control-lg" value="<%= params[:q] %>" maxlength="50">
                            <button type="submit" data-lang="vi-vn" class="search-button">
                              <i class="fa-solid fa-magnifying-glass"></i>
                            </button>
                          <% end %>
                        </div>    
                    </div>
                    <div class="col-sm-2" id="header-cart">
                        <div class="dropdown d-grid">
                            <button type="button" data-bs-toggle="dropdown" class="btn btn-inverse btn-block dropdown-toggle">
                              <i class="fa-solid fa-bag-shopping"></i>
                            </button>
                            <span class="mini-cart-count"><%= cart_items.count %></span>
                          
                            <ul class="dropdown-menu dropdown-menu-right" style="width: 500px; position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate3d(9px, 41px, 0px);" data-popper-placement="bottom-end">
                              <li>
                                <% if cart_items.any? %>
                                  <table class="table table-sm table-striped mini-tbl-product">
                                    <tbody>
                                      <% cart_items.each_with_index do |item, index| %>
                                        <tr>
                                          <td class="text-center">
                                            <a href="<%= product_detail_path(id: item[:id], slug: item[:slug]) %>">
                                              <img src="<%= url_for(item[:image]) %>" alt="<%= item[:name] %>" title="<%= item[:name] %>" class="img-thumbnail">
                                            </a>
                                          </td>
                                          <td class="text-start">
                                            <a href="<%= product_detail_path(id: item[:id], slug: item[:slug]) %>"><%= item[:name] %></a>
                                          </td>
                                          <td class="text-end">x <%= item[:quantity] %></td>
                                          <td class="text-end"><%= number_to_currency(item[:price] * item[:quantity], unit: 'VND', format: '%n %u', precision: 0) %></td>
                                          <td class="text-end">
                                            <%= form_with url: cart_remove_path, method: :post, data: { oc_target: "#header-cart" }, class: "d-inline" do |f| %>
                                            <%= hidden_field_tag :key, item[:id].to_s %>
                                            <button type="submit" data-bs-toggle="tooltip" class="btn btn-danger" aria-label="Loại bỏ">
                                                <i class="fa-solid fa-circle-xmark"></i>
                                            </button>
                                            <% end %>
                                          </td>
                                        </tr>
                                      <% end %>
                                    </tbody>
                                  </table>
                                  <div>
                                    <table class="table table-sm">
                                      <tbody>
                                        <tr>
                                          <td class="text-end"><strong>Tổng cộng</strong></td>
                                          <td class="text-end">
                                            <%= number_to_currency(cart_items.sum { |item| item[:price] * item[:quantity] }, unit: ' VND', format: '%n %u', precision: 0) %>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                    <p class="text-end">
                                      <a href="/cart"><strong><i class="fa-solid fa-bag-shopping"></i> Giỏ hàng</strong></a>&nbsp;&nbsp; | &nbsp;&nbsp;
                                      <% if cart_items.any? %> 
                                      <a href="/checkout"><strong><i class="fa-solid fa-share"></i> Thanh toán</strong></a>
                                      <% else %>
                                      <a href="/cart"><strong><i class="fa-solid fa-share"></i> Thanh toán</strong></a>
                                      <% end %>
                                      
                                    </p>
                                  </div>
                                <% else %>
                                  <p class="text-center">Giỏ hàng của bạn đang trống!</p>
                                <% end %>
                              </li>
                            </ul>
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/frontend/_main.html.erb
<main class="mb-3">
  <div class="container stk-menu">
    <nav id="menu" class="navbar navbar-expand-lg">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#narbar-menu">
        <i class="fa-solid fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="narbar-menu">
        <ul class="nav navbar-nav">
          <% @menuTree.each do |menu| %>
            <li class="nav-item dropdown">
              <a href="<%= product_menu_path(id: menu.id, slug: menu.slug) %>" class="nav-link dropdown-toggle">
                <%= menu.name %>
              </a>
              <% if menu.children.any? %>
                <div class="dropdown-menu">
                  <div class="dropdown-inner">
                    <ul class="list-unstyled">
                      <% menu.children.each do |child| %>
                        <li>
                          <a href="<%= product_menu_path(id: child.id, slug: child.slug) %>" class="nav-link">
                            <%= child.name %>
                          </a>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
  <div class="col-sm-12">
    <p class="header-notice">
      ĐẶT HOA ONLINE - GIAO MIỄN PHÍ TP HCM &amp; HÀ NỘI - GỌI NGAY 1900 123 456 HOẶC 1900 789 123
    </p>
  </div>
</main>

app/views/layouts/frontend/_nav.html.erb
<nav id="top">
    <div class="container">
        <div class="nav float-start">
            <ul class="list-inline">
                <li class="list-inline-item">HOTLINE: <a href="#">1900 123 456</a> | <a href="#">1900 789 123</a></li>
            </ul>
        </div>
        <div class="nav float-end">
            <ul class="list-inline">
                <li class="list-inline-item">
                    <div class="dropdown">
                        <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa-solid fa-user"></i> 
                            <span class="d-none d-md-inline"><%= t("account") %></span> 
                            <i class="fa-solid fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <% if current_user %>
                                <li><%= link_to t("account"), account_index_path, class: 'dropdown-item' %></li>
                                <li><%= link_to t("orderhistory"), account_order_path, class: 'dropdown-item' %></li>
                                <li><%= link_to t("logout"), account_logout_path, class: 'dropdown-item' %></li>
                            <% else %>
                                <li><%= link_to t("register"), home_register_path, class: 'dropdown-item' %></li>
                                <li><%= link_to t("login"), home_login_path, class: 'dropdown-item' %></li>
                            <% end %>
                        </ul>
                    </div>
                </li>
                <li class="list-inline-item"><a href="/cart" title="<%= t("cart") %>"><i class="fa-solid fa-bag-shopping"></i> <span class="d-none d-md-inline"><%= t("cart") %></span></a></li>
                <% if cart_items.any? %> 
                <li class="list-inline-item"><a href="/checkout" title="<%= t("pay") %>"><i class="fa-solid fa-share"></i> <span class="d-none d-md-inline"><%= t("pay") %></span></a></li>
                <% else %>
                <li class="list-inline-item"><a href="/cart" title="<%= t("pay") %>"><i class="fa-solid fa-share"></i> <span class="d-none d-md-inline"><%= t("pay") %></span></a></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/frontend/app.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="vi">

<head>
  <%= render 'layouts/frontend/head' %>
</head>

<body>
  <%= render 'layouts/frontend/nav' %>
  <%= render 'layouts/frontend/header' %>
  <%= render 'layouts/frontend/main' %>
  <%= yield %>
  <%= render 'layouts/frontend/footer' %>
  <%= render 'layouts/frontend/metu' %>

  <script src="/assets/frontend/js/index/script9.js"></script>
  <script src="/assets/frontend/js/index/script10.js"></script>
  <script src="/assets/frontend/js/index/script11.js"></script>
  <script src="/assets/frontend/js/index/script12.js"></script>
  <script src="/assets/frontend/js/index/script13.js"></script>
</body>

</html>